### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by yh406** [yh406/protospace-30541#1]
#URL
https://protospace-30541.herokuapp.com/

**Comment by MasaakiTanabashi** [comment]
原さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◎未ログインの状態でアクセスしたとき、ログイン画面が表示されます。
トップページが表示されるようにしましょう。
→カリキュラムの「ProtoSpaceのその他の機能を実装しよう『ユーザーのアクセス範囲の制限』」を確認しましょう。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yh406** [comment]
修正しました

**Comment by MasaakiTanabashi** [comment]
原さん、再提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◎投稿者以外のユーザーが、投稿者専用のページに遷移できないようにしましょう。
他のユーザーの投稿したプロトタイプ詳細ページのURLに直接「/edit」を入力するとエラー画面が表示されます。
→「prototypesコントローラーにおいて、投稿者以外がeditアクションにアクセスしたらトップページにリダイレクトするように記述した」こちらができているか、確認お願いします。
<img width="1420" alt="スクリーンショット 2020-10-13 19 22 11" src="https://user-images.githubusercontent.com/64255541/95848756-6ddfdb80-0d89-11eb-8710-d4d8f245be34.png">



修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yh406** [comment]
修正しました

**Comment by MasaakiTanabashi** [comment]
原さん、再提出ありがとうございます！
指摘させていただいた箇所、確認したところ状態に変化がないようにみられます。
再度修正をよろしくお願いします。

カリキュラムで正しい挙動を一度ご覧いただければと思います。
https://master.tech-camp.in/curriculums/5292
ユーザーのアクセス範囲の制限
・投稿者以外のユーザーが、投稿者専用のページに遷移できないようにしましょう


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yh406** [comment]
確認ありがとうございます。一つ質問させてください。

「他のユーザーの投稿したプロトタイプ詳細ページのURLに直接「/edit」を入力するとエラー画面が表示されます。」
こちらの件ですが、現状ではブラウザ上（ローカル）では特に動きに問題はなく、正常にトップページに戻リます。
明らかにコーディングが間違っているということでよろしいでしょうか？

**Comment by naokihayasan127** [comment]
原さん、再提出ありがとうございます！
ご質問有難うございます！

結論：本番環境では 「/edit」を入力すると以下のようなページになっております。
<img width="1440" alt="スクリーンショット 2020-10-14 9 35 59" src="https://user-images.githubusercontent.com/65150371/95930167-ca321200-0e00-11eb-8a21-e94213bac5f7.png">

本来であれば、他者の編集ができないようにトップページに遷移するような作りにする必要があります。
・リダイレクトの処理に誤りがあるのではないでしょうか。
https://master.tech-camp.in/curriculums/5292
カリキュラムの最後を参考に作業してみてください。

**Comment by yh406** [comment]
もう一度確認しましたが、カリキュラム内のgif動画のように直接URLでeditを入れても、
トップページへのリダイレクトは行えているのですが、何かおかしいところがあるのでしょうか？

**Comment by naokihayasan127** [comment]
再度、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

先程まで私の方でも確認しておりましたが、反映まで時間がかかっていたのか理由は定かではありませんが今、再度確認したところ正常に動作しておりましたのでLGTMとさせていただきます。お疲れ様でした！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
